version: '2'

services:
        mongo:
                image: mongo
                restart: always
                volumes:
                - ${PWD}/data/db:/data/db
                ports:
                - "27017:37017"
                container_name: "mongo-mosq"
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: changeme

        mosquitto:
                build: .
                volumes:
                - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
                ports:
                - "1883:1883"
                - "9883:9883"
                environment:
                - DOMAIN=example.local
                - PORT=8080
                depends_on:
                - mongo
                labels:
                - "local.example.description=Mosquitto v1.6.9 MQTT server"

